### ISSUE TITLE
Let's select a paper for our paper reading/discussion session on July 18, 2020

### ISSUE THREAD

**Issue by omarsar** [dair-ai/nlp-paper-discussions#7]
Suggest a paper you would like us to discuss during our weekly paper reading discussion. It can be a paper from RL, Computer Vision, NLP, or any ML related paper.

You can vote on a suggested paper by using the 👍 emoji. I will close the issue in one or two days and select the paper with the most votes. Then I will make the announcement at the beginning of the week. Thanks.

**Comment by askmuhsin** [comment]
### Bootstrap Your Own Latent
A New Approach to Self-Supervised Learning

_paper_ : https://arxiv.org/pdf/2006.07733.pdf

**abstract**
We introduce Bootstrap Your Own Latent (BYOL), a new approach to self-supervised image
representation learning. BYOL relies on two neural networks, referred to as online and target
networks, that interact and learn from each other. ...

**Comment by manisnesan** [comment]
### Deep Learning Based Text Classification: A Comprehensive Review

paper: http://arxiv.org/abs/2004.03705v1

**abstract**
Deep learning based models have surpassed classical machine learning based approaches in various text classification tasks, including sentiment analysis, news categorization, question answering, and natural language inference. In this work, we provide a detailed review of more than 150 deep learning based models for text classification developed in recent years, and discuss their technical contributions, similarities, and strengths. We also provide a summary of more than 40 popular datasets widely used for text classification. Finally, we provide a quantitative analysis of the performance of different deep learning models on popular benchmarks, and discuss future research directions.

**Comment by tathaghosh** [comment]
**Politeness Transfer: A Tag and Generate Approach**
paper:[https://arxiv.org/abs/2004.14257](https://arxiv.org/abs/2004.14257)

**Abstract**
This paper introduces a new task of politeness transfer which involves converting non-polite sentences to polite sentences while preserving the meaning. We also provide a dataset of more than 1.39 instances automatically labeled for politeness to encourage benchmark evaluations on this new task. We design a tag and generate pipeline that identifies stylistic attributes and subsequently generates a sentence in the target style while preserving most of the source content. For politeness as well as five other transfer tasks, our model outperforms the state-of-the-art methods on automatic metrics for content preservation, with a comparable or better performance on style transfer accuracy. Additionally, our model surpasses existing methods on human evaluations for grammaticality, meaning preservation and transfer accuracy across all the six style transfer tasks

**Comment by omarsar** [comment]
We will be going over the "Deep Learning Based Text Classification: A Comprehensive Review" paper according to votes. Thanks for the suggestions, everyone.
